### ISSUE TITLE
View only should show the remote cursor

### ISSUE THREAD

**Issue by agronick** [novnc/noVNC#974]
The Readme lists under features "Local or remote cursor". As far as I can tell this option was disabled and Remote cursors will be used whenever they are available. However, on view only connections the users see no cursor with buttons being clicked by an invisible cursor.

I was able to fix this by changing these two lines

In _negotiate_server_init:
```
this._display.disableLocalCursor();
```
to 
```
if (!this._viewOnly)
    this._display.disableLocalCursor();
```
In _sendEncodings
```
            if ((0, _browsers.browserSupportsCursorURIs)() && !_browsers.isTouchDevice && this._fb_depth == 24) {
                encs.push(_encodings.encodings.pseudoEncodingCursor);
            }
```
to
```
            if ((0, _browsers.browserSupportsCursorURIs)() && !_browsers.isTouchDevice && this._fb_depth == 24) {
                if (!this._viewOnly)
                    encs.push(_encodings.encodings.pseudoEncodingCursor);
            }
```

It would be nice if some of the options were restored such as the ability to have local and remote cursor. So helpdesk people can see exactly what is happening on the users screen and what they are clicking.

**Comment by DirectXMan12** [comment]
Seems reasonable.

@samhed  @CendioOssman WDYT

**Comment by samhed** [comment]
Agreed, sounds good. I'll commit.

> The Readme lists under features "Local or remote cursor". As far as I can tell this option was disabled and Remote cursors will be used whenever they are available.

This documentation issue is addressed in #971

**Comment by samhed** [comment]
@CendioOssman asked me to hold off with committing, said he has an objection.

**Comment by CendioOssman** [comment]
Yeah, I don't think this is the best way to solve this. This is a server bug IMO as it should not be sending a local cursor if it wants to control the position. Even if we change this it will still be broken if "view only" is turned off. So extra complexity for us without a proper fix for the fundamental problem.

What server are you using?

**Comment by samhed** [comment]
> The easiest fix is to just add the option back in, IMO.

What do you mean?

**Comment by CendioOssman** [comment]
> I'm not certain there's a good way for the sever to know when the user wants to control cursor position.

It's actually rather simple. The server can compare the current cursor position with the last requested by the client. If they differ then the server needs to render the cursor. This is implemented in the RealVNC code base, so every server based on that includes this behaviour.

> In some view-only scenarios (e.g. a presentation), the user doesn't care about cursor position...

In that scenario the user wants no cursor at all, not a server rendered one.


So I still see no compelling reason to add this. The issues I see are:

a) Adding interfaces with the sole rationale of "work around bugs" is user unfriendly and a very slippery slope and should be a very last resort kind of thing.
b) It's not even a good workaround here as it does not solve the issue of a shared session properly. As soon as "view only" is off then the problem would be back.

@agronick, what server is this and have you talked to the server developer about this issue?

**Comment by agronick** [comment]
Most of our connections are using x11vnc. This is being used for remote support. Certain systems have sensitive information and the support personnel are not allowed to control it. It was reported by our users that they wanted to see what the people in the stores were clicking. 

I certainly think that situations where the user would not want the cursor shown on view only are going to be in the minority. And even if I was doing a presentation I might want my cursor to be shown so I can point things out.

If the code I outlined is the correct way to do it. It seems at the very least this should be made a configuration option.

I really don't understand why you are saying x11vnc is broken. It hides the cursor when you ask it to.

**Comment by CendioOssman** [comment]
The problem is that your change would only solve the shared case for clients using "view only". If you have a collaborative session you don't want to have to fiddle with the settings every time someone else takes control.

The only way to make this work for everyone is in the server, because only the server knows what all clients are up to. Hence why I'm saying x11vnc is broken. It should only be sending the local cursor to a single client (the one who last moved the cursor). Every other client should be getting a server side cursor.

**Comment by agronick** [comment]
All I'm asking for is to show it for view only. I think when you have full control it definitely makes sense to render it client side. The changes I gave only showed the remote cursor on view only.

**Comment by CendioOssman** [comment]
I understand what you are asking for. But I'm saying that I consider that a workaround, not a fix, and a partial one at that. The proper solution IMO is to file a bug with x11vnc and get them to fix their handling of local cursors.

**Comment by DirectXMan12** [comment]
Honestly, I don't see it as a whole lot of extra complexity for a win for a user (IMO, it shouldn't be hard for users who really want to to enable or disable *any* encoding or pseudo-encoding, but that's a different story).

>Adding interfaces with the sole rationale of "work around bugs" is user unfriendly and a very slippery slope and should be a very last resort kind of thing.

You're never going to get server developers to do everything you want as a client, and they'll just bounce users back to us saying "oh, it's an easier fix in the client".  That's the life of being a library or client author.  You'll just drive users away or make them frustrated, in my experience (from both sides of this equation).  I get not wanting to have a bunch of hacky work-arounds, but to me, this doesn't even feel like a hack -- it's just allowing a user to say "on, off, auto" instead of just "auto" for a feature.

> It's not even a good workaround here as it does not solve the issue of a shared session properly. As soon as "view only" is off then the problem would be back.

I'd just add back in an "advanced" option that allows enabling or disabling local cursor.  The default would be "auto" (what we currently have), but if the user knows better, they can manually set it to on or off.

**Comment by CendioOssman** [comment]
It is a hack if the only rationale is to work around bugs, not because there is some trade-off we need the user to decide on.

But I've listed my objections and so far I don't see any changes to that. I won't block this if I'm the minority, but my vote is unfortunately still no. Mainly so because of clutter in the interface. Code complexity is negligible here.

(and the setting would really be "force off" as we've never had a "force on" for this)

**Comment by sebas88** [comment]
@agronick Thank you very much for sharing the solution. I bumped into the same issue and was able to fix with your changes.

**Comment by samhed** [comment]
I'm fine either way, if it's a common use case I don't mind having a setting.

**Comment by DirectXMan12** [comment]
I'm going to move this to future features, and then I'll try and write up what I suggested earlier when I get the chance, unless @agronick wants to try and do so.
